### ISSUE TITLE
A Page for Ethereum Testnets

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/ech-website-v2#115]
### Active
- Holesky 
- Sepolia
- Goerli
### Deprecated
- Old Testnets

Info to be added 
- Explorers
- Faucets
- GitHub
- Tutorials (if any)

**Comment by darigovresearch** [comment]
Believe this page is live with all of the above items - https://www.ethereumcatherders.com/testnets/

However only found this page by noticing it in the GitHub files.

Has this already been linked somewhere in the site or does it need to be added to activities?

**Comment by geovgy** [comment]
Yes, a navigation link to the testnet page was added later in the sub-navigation bar. This is finished so closing this issue now.
