### ISSUE TITLE
Home screen -- html index are seen in the URLs 

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/ech-website-v2#2]
We see that index.html is linked to the home page url and the rest of the sub links; it must be removed. “https://www.ethereumcatherders.com/index.html”.  Expected: https://www.ethereumcatherders.com/ 

E.g:

1. https://ethereumcatherders.com/calendar.html
2. https://ethereumcatherders.com/blog.html

**Comment by poojaranjan** [comment]
Removed .html as per #29
