### ISSUE TITLE
Page layout change - EIP Resources

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/ech-website-v2#22]
We're looking for an improved layout of the page to provide a quick feel of the contents available on the page.

- [ ] Update current text with
 "EIP stands for Ethereum Improvement Proposal. An EIP is a design document providing information to the Ethereum community, or describing a new feature for Ethereum or its processes or environment. The EIP should provide a concise technical specification of the feature and a rationale for the feature. 
We curate the resources for proposals in active discussion and also produce a [PEEPanEIP](https://www.youtube.com/playlist?list=PL4cwHXAawZxqu0PKKyMzG_3BJV_xZTi1F) video series focused on the EIPs and features of the upcoming Ethereum network upgrades."

- [x] Change the overall font size to adjust more content 
- [x] Change the new layout as below 

![image](https://user-images.githubusercontent.com/29681685/132541638-28376a73-3b65-4d2a-a284-ca97f8235361.png)

**Comment by Samarth-001** [comment]
Mam Issue resolved. But I need push access to the repository to upload it.

**Comment by poojaranjan** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/29681685/184955228-55485b03-0a56-4005-bdeb-e899e6239a55.png">

- [  ] Add link to PEEPanEIP as shared in the above comment


cc: @Samarth-001

**Comment by poojaranjan** [comment]
fixed with #63
