### ISSUE TITLE
Read our journey with Ethereum ecosystem - Review 2021 - Has to be updated

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/ech-website-v2#24]
In the home page currently, the "Read our journey with Ethereum ecosystem - Review 2020: The Ethereum Cat Herders", we do have 2021 mid year report here: https://medium.com/ethereum-cat-herders/the-ethereum-cat-herders-mid-year-report-3fb89b57dbdf
![image](https://user-images.githubusercontent.com/27824858/133187061-b7e21237-f1a7-43c4-ab12-ae1f94ef4b7f.png)

The message should be changed to "**Read our journey with the Ethereum ecosystem - Review 2021 mid year**" and should link to the above URL.

@poojaranjan:I believe it will be a high priority item, given that we want everyone to be aware of what we are doing right now.

**Comment by poojaranjan** [comment]
added as per #29
