### ISSUE TITLE
Youtube option under latest videos are hidden

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/ech-website-v2#3]
We are unable to see the full view of the Youtube options under the Video player for the “Latest videos.” reference: https://share.getcloudapp.com/7KuoxzE6

**Comment by poojaranjan** [comment]
@Santhosh1692 could you confirm if this issue is still there or has been addressed?

**Comment by minimalsm** [comment]
Fixed for me.

**Comment by Santhosh1692** [comment]
It is fixed. Closing the issue.
