### ISSUE TITLE
Activity:Network Upgrades -- alignment issue

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/ech-website-v2#6]
The label “Network Upgrade Process Tracker” is not center aligned. https://share.getcloudapp.com/12u4E7g0

**Comment by minimalsm** [comment]
I think this is resolved?

<img width="1081" alt="Screenshot 2021-09-13 at 21 19 51" src="https://user-images.githubusercontent.com/62268199/133150818-ae807560-2b7d-495e-afdc-b7f4ce1edf39.png">

**Comment by Santhosh1692** [comment]
It is fixed. Closing the issue.
