### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by omahs** [ethereum-cat-herders/ech-website-v2#69]
Hey, there's a few broken links on the website:

<img width="1164" alt="A" src="https://user-images.githubusercontent.com/73983677/191683133-478386f2-c13c-425b-89a4-fd109f07cda9.png">

I used this tool to check that: https://www.brokenlinkcheck.com/

**Comment by poojaranjan** [comment]
Thanks for sharing. Fixed with #73
