### ISSUE TITLE
Activity:Network Upgrades -- Clicking on title takes you to the top of the screen

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/ech-website-v2#7]
Clicking on the title of the upgrades leads you to the top of the screen, which is a bug: https://share.getcloudapp.com/YEuZveDy

**Comment by poojaranjan** [comment]
I suppose, adding a screenshot will be helpful.

**Comment by poojaranjan** [comment]
@Santhosh1692 please confirm if the issue has been resolved, if so we can close the issue.

**Comment by Santhosh1692** [comment]
It is fixed. Closing the issue.
