### ISSUE TITLE
Activity:Network Upgrades -- Date is missing for the DAO Wars

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/ech-website-v2#8]
DAO Wars: Information (such as; date) is missing from previous Ethereum blockchain updates, according to a reference: 
![image](https://user-images.githubusercontent.com/27824858/124731181-a040f280-df2f-11eb-90f6-d873bcd2530e.png)

**Comment by poojaranjan** [comment]
@Santhosh1692 can you also add the link where on the Ethereum Cat Herders website it needs to be updated?

**Comment by poojaranjan** [comment]
Add date  - June 24, 2016
![image](https://user-images.githubusercontent.com/29681685/132536669-5898e731-3841-4bfe-bafe-bbe4bb5dd1e0.png)

cc: @michaelgiesen @jerik-unvetica

**Comment by poojaranjan** [comment]
fixed as per #23
