### ISSUE TITLE
Update Home page

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/ech-website-v2#90]
# 1. Add Discord link
<img width="751" alt="image" src="https://user-images.githubusercontent.com/29681685/213337062-c5cb8144-b18a-4ffd-92b6-45d6a9d97e27.png">

Remove "Ethereum Ecosystem" (right side) instead embed Discord link like this 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/29681685/213337372-394b502f-8207-472b-a742-904f07d3fa9a.png">

# 2.  Add Tim Beiko to 
<img width="697" alt="image" src="https://user-images.githubusercontent.com/29681685/213337580-9f0c74ff-5a26-48ad-af5c-daad9bfd8333.png">

“Wanted to share I think[ @EthCatHerders](https://twitter.com/EthCatHerders) are awesome: they help make ACD and other protocol-related things accessible to more folks with transcripts, blog posts, and video series. It’s also a great way to onboard new Ethereum contributors ” [Tim Beiko](https://twitter.com/TimBeiko/status/1455974435970633728)

# 3. Community Supporter

Add a carousal to display logo and name of organizations 

- Moloch DAO - https://molochdao.com/
- Ecosystem Support Program - https://esp.ethereum.foundation/
- Gitcoin grant - https://gitcoin.co/grants/782/ethereum-cat-herders-community-fund
- Fellowship of Ethereum Magicians - https://ethereum-magicians.org/
- https://entethalliance.org/

**Comment by darigovresearch** [comment]
Can confirm that all items mentioned in this issue is on the site and so issue can be closed.

https://www.ethereumcatherders.com/
